config/routes.rb
DakarParties::Application.routes.draw do
  

  get '/new_sms' => 'djanoa_messages#new_sms', defaults: {format: 'xml'}

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "home/index"

  devise_for :users

  ActiveAdmin.routes(self)

  resources :partenaires

  resources :events

  resources :actualites

  resources :annonces

  resources :category_annonces

  resources :lieus

  resources :category_actus

  resources :category_events

  resources :structures

  resources :users

  resources :galeries

  resources :category_galeries

  root :to => 'home#index'

end

app/models/actualite.rb
class Actualite < ActiveRecord::Base
  belongs_to :categoryActu
  attr_accessible :contenu, :titleActu, :categoryActu_id, :picture

  validates :contenu, :presence  => true
  validates :titleActu, :presence  => true

  mount_uploader :picture, PictureUploader
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_id
  # attr_accessible :title, :body
end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
  belongs_to :categoryAnnonce
  attr_accessible :date_debut, :date_fin, :descAnnonce, :titleAnnonce

  validates :titleAnnonce, :presence  => true
  validates :descAnnonce, :presence  => true
  
end

app/models/category_actu.rb
class CategoryActu < ActiveRecord::Base
  has_many :actualites
  attr_accessible :descCategory, :titleCategory
end

app/models/category_annonce.rb
class CategoryAnnonce < ActiveRecord::Base
  has_many :annonces
  attr_accessible :descCategory, :titleCategory
end

app/models/category_event.rb
class CategoryEvent < ActiveRecord::Base
  has_many :events
  attr_accessible :descCategory, :titleCategory
end

app/models/category_galerie.rb
class CategoryGalerie < ActiveRecord::Base
  has_many :galeries
  attr_accessible :desc, :titleCategory

  validates :titleCategory, :presence  => true
end

app/models/djanoa_message.rb
class DjanoaMessage < ActiveRecord::Base
  attr_accessible :from, :to, :message

  # Return the words off the sms
  # @return [Array]

  def words
    message.split
  end

  def method_missing(m, *args)
    if m.to_s[/word_(.+)_exists?/]
      return false if $1.to_i.zero?
      return !words[$1.to_i-1].nil?
    elsif m.to_s[/word_(.+)/]
      return nil if $1.to_i.zero?
      return words[$1.to_i-1]
    else
      super
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :categoryEvent
  belongs_to :structure
  belongs_to :lieu
  belongs_to :user
  attr_accessible :annuler, :date_debut, :date_fin, :descEvent, :nombrePersonne, :titleEvent, :picture, :heure_fin, :heure_debut, :user_id
  attr_accessible :categoryEvent_id, :structure_id, :lieu_id
  mount_uploader :picture, PictureUploader
  validates :titleEvent, :presence  => true
  validates :descEvent, :presence  => true

  validates :heure_debut, :presence  => true
  validates :heure_fin, :presence  => true
  validates_presence_of :categoryEvent_id
  validates_presence_of :lieu_id
  validates_presence_of :structure_id

  # def self.search(search)
  # search_condition = "%" + search + "%"
  # find(:all, :conditions => ['titleEvent LIKE ? OR descEvent LIKE ?', search_condition, search_condition])
  # end

end

app/models/galerie.rb
class Galerie < ActiveRecord::Base
  belongs_to :categoryGalerie
  attr_accessible :picture, :title

  validates :title, :presence  => true
end

app/models/lieu.rb
class Lieu < ActiveRecord::Base
  has_many :events
  attr_accessible :NomRegion, :descLieu, :nomLieu
end

app/models/partenaire.rb
class Partenaire < ActiveRecord::Base

  belongs_to :structure
  attr_accessible :descPartenaire, :email, :nomPartenaire, :telephone
  validates :nomPartenaire, :presence  => true
end

app/models/structure.rb
class Structure < ActiveRecord::Base
  has_many :events
  has_many :partenaires
  attr_accessible :adresse, :descStructure, :email, :nomStructure, :telephone
  validates :nomStructure, :presence  => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :admin, :adminActu, :adminEvent, :adresse, :datenaiss, :login, :nom, :prenom, :sexe, :telephone

  validates :email,        :presence => true,
    :format         => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i},
    :uniqueness     => true
  validates :telephone, :presence  => true

  scope :garcons,         where(:sexe => true)
  scope :filles,          where(:sexe => false)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/actualites_helper.rb
module ActualitesHelper
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end
end

app/helpers/lieus_helper.rb
module LieusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_actu.erb
<% actus=Actualite.all%>
<% if !actus==nil?%>
    <% actus.each do |actu| %>
<!-- Begin of rows -->
<div class="row carousel-row">
  <div class="col-xs-8 col-xs-offset-2 slide-row">
    <div id="carousel-1" class="carousel slide slide-carousel" data-ride="carousel">

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag(actu.picture_url, :width => 150, :height => 150) if actu.picture.present? %>

        </div>
      </div>
    </div>
    <div class="slide-content">
      <h4 style="background-color:#15928e; color:#000"><%=link_to actu.titleActu, actu%></h4>
      <p>
        <%= actu.contenu[0..230].gsub(/\s\w+\s*$/, '...')%>
      </p>
    </div>
    <div class="slide-footer">
                 <i class="icon-calendar"> <%= actu.created_at.strftime("%d %B %Y") %></i>
                <span class="pull-right buttons">
                    <%=link_to raw('<button class="btn btn-sm btn-mini btn-primary"> Lire la suite </button>') , actu %>
                </span>
    </div>
  </div>
</div>

<% end %>

<% end %>

<%= link_to raw('<span class="btn btn-primary" style="margin-left: 40%"> Voir Tout <i class="icon-plus icon-white" ></i></span>'), actualites_path%>

app/views/home/_events_jour.erb
<% event_days=Event.all.reverse %>
<% compte=0 %>
<% if !event_days.nil?   %>


                    <% event_days.each do |event_day| %>
                        <% if event_day.date_debut == Date.today   %>

                          <% compte +=1%>
                          <% lieu=Lieu.find_by_id(event_day.lieu_id)%>




                      <table style="margin-bottom:10px;">
                      <tr >
                        <td><%= image_tag(event_day.picture_url, :width => 240, :height => 120) if event_day.picture.present? %></td>
                        <td>
                          <table class="" style="">
                             <% modal="myModal"+event_day.id.to_s%>
                            <% hmodal="#"+modal %>
                             <tr>
                                <td><span style="font-size:1.3em;"> Le :  <%= event_day.date_debut.strftime("%A %d %B %Y") %></span></td>
                            </tr>
                            <tr>
                              <td><span style="font-size:1.3em;">Lieu: <%= lieu.nomLieu%></span></td>
                            </tr>
                            <tr>
                                <td><span style="font-size:1.2em;"><%= event_day.descEvent %></span></td>
                            </tr>


                              <tr>

                                        <td><span class="btn btn-mini btn-primary" data-toggle="modal" href=<%= hmodal%>><i class="icon-plus-sign icon-white"></i> <a>Voir l'événement</a> </span> <%= social_share_button_tag(event_day.descEvent, :url => "http://www.facebook.com") %></td>
                              </tr>


                          </table>
                        </td>
                      </tr>
                      </table>




                      <div id=<%=modal%> class="modal hide fade">
                      <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h3>Details de l'événement</h3>
                      </div>
                      <div class="modal-body">

                                    <table class="table">
                                      <tr>
                                  <td><%= image_tag(event_day.picture_url, :width => 240, :height => 120) if event_day.picture.present? %></td>
                                  </tr>
                                      <tr>
                                          <td><%= event_day.titleEvent %></td>
                                      </tr>
                                      <tr>
                                          <td><%= event_day.descEvent %></td>
                                      </tr>
                                      <tr>

                                          <td><span style="font-size:1.2em">Date: </span><% event_day.date_debut.strftime("%A %d %B %Y") %></td>
                                      </tr>
                                      <tr>
                                          <td><span style="font-size:1.2em">Heure de début: </span><%= event_day.heure_debut.strftime("%H : %M")%></td>
                                      </tr>
                                      <tr>
                                      <td><span style="font-size:1.2em">Lieu: </span><%= lieu.nomLieu%></td>
                                      </tr>


                                      <tr>
                                          <td><span style="font-size:1.2em">nomde de personne: </span><%= event_day.nombrePersonne %> participants</td>
                                      </tr>

                                </table>
                      </div>
                      <div class="modal-footer">
                        <a href="#" class="btn btn-primary" data-dismiss="modal" >Close</a>

                      </div>
                    </div>


                      <% end %>
                      <% end %>
                       <% if compte ==0 %>



                        <div class="alert alert-success">
                          <a class="close" data-dismiss="alert"></a>
                          <span style="font-size: 1.5em; font-family: 'Glyphicons Halflings'" > Hello! Nous avons pas d'événement pour aujourd'hui <%= image_tag("smile2.png", :width => 50)%></span>
                        </div>
                       <% end %>

                    <% end %>

app/views/home/_events_mois.erb
<% event_days=Event.all %>
<% compte=0 %>
<% if !event_days==nil?%>
                    <% event_days.each do |event_day| %>
                    <% if (event_day.date_debut >=Date.today) and (event_day.date_debut <= event_day.date_debut.next.at_end_of_month)%>
                          <% lieu=Lieu.find_by_id(event_day.lieu_id)%>
                          <% compte += 1 %>
                          <% structure=Structure.find_by_id(event_day.structure_id)%>
            <table style="margin-bottom:10px;">
              <tr >
                <td><%= image_tag(event_day.picture_url, :width => 240, :height => 120) if event_day.picture.present? %></td>
                <td>
                <table class="" style="">
                  <% modal="myModal"+event_day.id.to_s%>
                  <% hmodal="#"+modal %>
                  <tr>
                    <td><span style="font-size:1.3em;"> Le :  <%= event_day.date_debut.strftime("%d-%m-%Y") %></span></td>
                  </tr>
                  <tr>
                    <td><span style="font-size:1.3em;">Lieu: <%= lieu.nomLieu%></span></td>
                  </tr>
                  <tr>
                    <td><span style="font-size:1.2em;"><%= event_day.descEvent %></span></td>
                  </tr>


                  <tr>

                    <td><span class="btn btn-mini btn-primary" data-toggle="modal" href=<%= hmodal%>><i class="icon-plus-sign icon-white"></i> <a>Voir l'événement</a> </span> <%= social_share_button_tag(event_day.descEvent, :url => "http://www.facebook.com") %></td>
                  </tr>


                </table>
              </td>
              </tr>
            </table>
                       <hr/>

                      <% end %>
                      <% end %>
                    <% if compte ==0 %>
        <div class="alert alert-success">
          <a class="close" data-dismiss="alert"></a>
          <span style="font-size: 1.5em; font-family: 'Glyphicons Halflings'" > Hello! Nous avons pas d'événement pour cette semaine <%= image_tag("smile2.png", :width => 50)%></span>
        </div>
                    <% end %>


                    <% end %>

app/views/home/_events_week.erb
<% event_days=Event.all %>
<% compte = 0%>
<% if !event_days==nil?%>
                    <% event_days.each do |event_day| %>
                    <% if (event_day.date_debut >=Date.today) and (event_day.date_debut <= event_day.date_debut.next.at_end_of_week)%>
                          <% lieu=Lieu.find_by_id(event_day.lieu_id)%>
                           <%compte +=1%>
                          <% structure=Structure.find_by_id(event_day.structure_id)%>
            <table style="margin-bottom:10px;">
              <tr >
                <td><%= image_tag(event_day.picture_url, :width => 240, :height => 120) if event_day.picture.present? %></td>
                <td>
                <table class="" style="">
                  <% modal="myModal"+event_day.id.to_s%>
                  <% hmodal="#"+modal %>
                  <tr>
                    <td><span style="font-size:1.3em;"> Le :  <%= event_day.date_debut.strftime("%d-%m-%Y") %></span></td>
                  </tr>
                  <tr>
                    <td><span style="font-size:1.3em;">Lieu: <%= lieu.nomLieu%></span></td>
                  </tr>
                  <tr>
                    <td><span style="font-size:1.2em;"><%= event_day.descEvent %></span></td>
                  </tr>


                  <tr>

                    <td><span class="btn btn-mini btn-primary" data-toggle="modal" href=<%= hmodal%>><i class="icon-plus-sign icon-white"></i> <a>Voir l'événement</a> </span> <%= social_share_button_tag(event_day.descEvent, :url => "http://www.facebook.com") %></td>
                  </tr>


                </table>
              </td>
              </tr>
            </table>

                       <hr/>

                      <div id=<%=modal%> class="modal hide fade">
                      <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h3>Details de l'événement</h3>
                      </div>
                      <div class="modal-body">

                                    <table class="table">
                                      <tr>
                                  <td><%= image_tag(event_day.picture_url, :width => 240, :height => 120) if event_day.picture.present? %></td>
                                  </tr>
                                      <tr>
                                          <td><%= event_day.titleEvent %></td>
                                      </tr>
                                      <tr>
                                          <td><%= event_day.descEvent %></td>
                                      </tr>
                                      <tr>
                                          <td><span style="font-size:1.2em">Date: </span> <%= event_day.date_debut %></td>
                                      </tr>
                                      <tr>
                                          <td><span style="font-size:1.2em">Heure: </span><%= event_day.heure_debut.strftime("%Ih : %M")%></td>
                                      </tr>
                                      <tr>
                                      <td><span style="font-size:1.2em">Lieu: </span><%= lieu.nomLieu%></td>
                                      </tr>

                                      <tr>
                                         <td><span style="font-size:1.2em">Heure: </span><%= event_day.heure_fin.strftime("%Ih : %M") %></td>
                                      </tr>
                                      <tr>
                                          <td><span style="font-size:1.2em">nomde de personne: </span><%= event_day.nombrePersonne %></td>
                                      </tr>

                                </table>
                      </div>
                      <div class="modal-footer">
                        <a href="#" class="btn btn-primary" data-dismiss="modal" >Close</a>

                      </div>
                    </div>
                      <% end %>
                      <% end %>
                    <% if compte ==0 %>
                        <div class="alert alert-success">
                          <a class="close" data-dismiss="alert"></a>
                          <span style="font-size: 1.5em; font-family: 'Glyphicons Halflings'" > Hello! Nous avons pas d'événement pour ce mois <%= image_tag("smile2.png", :width => 50)%></span>
                        </div>
                    <% end %>


                    <% end %>

app/views/home/_nav_actu.html.erb
<div class="span3" style="width:22%" >


  <% if user_signed_in? %>
      <% user= current_user%>


      <ul class="nav nav-pills nav-stacked" style="text-align: justify">
        <li class="active">
          <a href="#" style="text-align:center"><i class="icon-user icon-white"></i> Bienvenue <%= current_user.login %></a>
        </li>
        <li class=""><%= link_to raw(" <center> <i class='icon-eye-open icon-black' style=''> Mon profil</i> </center>"), user, :class => 'well' %></li>
        <li class=""><%= link_to raw(" <center> <i class='icon-pencil icon-black' style=''> Modifier profil</i> </center>"),edit_user_path(user), :class => 'well' %></li>

        <li ><%= link_to raw(" <center> <i class='icon-off icon-black' style=''> Deconnexion</i></center>"), destroy_user_session_path, :method => :delete, :class => 'btn btn-large', :notice => 'nice' %></li>

      </ul>

          <div class="clearfix"></div>




  <% else %>
         <ul class="nav nav-pills nav-stacked " style="text-align: justify;padding:10px">
          <li class="active">
            <a href="#" style="text-align:center"><i class="icon-user icon-white"></i> Espace membre</a>
          </li>
          <li class=""><%= link_to raw(" <center> <i class='icon-hand-right icon-black' style=''> Se connecter</i> </center>"), new_user_session_path, :class => 'well' %>
          </li>
          <li class=""> <%= link_to raw("<center> <i class='icon-plus icon-black' style=''> S'inscrire</i> </center>"), new_user_registration_path, :class => 'well'%></li>
        </ul>

  <% end %>


               <% event_days=Event.all(:limit => 3)%>
                    <% if !event_days.nil?%>
                    <% event_days.each do |event_day| %>

                          <% lieu=Lieu.find_by_id(event_day.lieu_id)%>
                          <% structure=Structure.find_by_id(event_day.structure_id)%>

            <div  class="well sidebar-nav" style="background-color:#931869; width:100%;color:#fff;border:3px solid #044d47" >
              <ul class="nav nav-pills nav-stacked" style="text-align: justify; padding:10px">
                <li class="active" style="">
                  <%= image_tag(event_day.picture_url, :width => 200, :height => 100) if event_day.picture.present? %>
                  <%=link_to event_day.titleEvent, root_path%>
                </li>
                <li  >
                  <span style=" color:#000;"></span><i class="icon-calendar"></i>  <%= event_day.date_debut.strftime("%d-%m-%Y")%>
                </li>
                <li  >
                  <span style=" color:#000;"></span> <i class="icon-time"></i> <%= event_day.heure_debut.strftime("%H")%>H : <%= event_day.heure_debut.strftime("%M")%>
                </li>
                <li  >
                  <span style=" color:#000;"></span> <i class="icon-map-marker"></i>  <%= lieu.nomLieu%>
                </li>




              </ul>

            </div>

                <% end %>
                <% end %>



              <ul class="nav nav-pills nav-stacked" style="text-align: justify">
                      <li class="active">
                        <a href="#">Actualités  </a>
                      </li>
              </ul>
                    <% actus=Actualite.all(:limit => 3)%>
                    <% if !actus==nil?%>
                    <% actus.each do |actu| %>

              <div  class="well sidebar-nav" style="background-color:#931869; width:100%;color:#fff;border:3px solid #044d47" >
                  <ul class="nav nav-pills nav-stacked" style="text-align: justify; padding:10px">
                    <li class="active" style="">
                        <%=link_to actu.titleActu, actu%>
                        <%= image_tag(actu.picture_url, :width => 240, :height => 120) if actu.picture.present? %>

                    </li>

                    <li class="active" style="">
                        <%= actu.contenu[0..30].gsub(/\s\w+\s*$/, '...')%>


                    </li>



                  </ul>

                </div>


                <% end %>
                <% end %>










            </div><!--/span-->

app/views/home/index.html.erb
                             <!-- Carousel-->

      <div class="row-fluid" style="">
 
            <div class="span9" style="width:73%">
              <% if flash[:notice] and  (user_signed_in?) %>
                <div class="alert alert-success">
                  <a class="close" data-dismiss="alert">×</a>
                  <%= raw flash[:notice] %>
                </div>

              <% end %>
              <% if flash[:alert] %>
                <div class="alert alert-success">
                  <a class="close" data-dismiss="alert">×</a>
                  <%= raw flash[:alert] %>
                </div>

              <% end %>

              <div id="myCarousel" class=" " style="border:1px solid #044d47; margin-bottom: 5px">
                <div class="carousel-inner">
                  <div class="item active" style="">
                     <%=link_to image_tag("slide4.jpg"), root_path, :title => 'dakarParties'%>

                  </div>


                </div>

              </div>

              <div class="tabbable" style="margin-bottom: 18px;">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#tab1" data-toggle="tab" style="background-color:#15928e;font-size:2em ;color:#fff">Aujourd'hui!</a></li>
                  <li class=""><a href="#tab2" data-toggle="tab" style="background-color:#148581;font-size:1.5em ;color:#fff">Cette semaine!</a></li>
                  <li class=""><a href="#tab3" data-toggle="tab" style="background-color:#0d5a56;font-size:1.2em ;color:#fff">Ce mois!</a></li>
                </ul>
                <div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
                  <div class="tab-pane active" id="tab1">



                    <%= render :partial => 'home/events_jour' %>


                  </div>
                  <div class="tab-pane" id="tab2">


                    <%= render :partial => 'home/events_week' %>

                  </div>

                  <div class="tab-pane" id="tab3">

                    <%= render :partial => 'home/events_mois' %>

                  </div>



                </div>

                <div>
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab1" data-toggle="tab" style="background-color:#15928e;font-size:2em ;color:#fff">Actualités</a></li>
                  </ul>

                  <%= render :partial => 'home/actu' %>
                </div>
              </div>

            </div>


            <%= render :partial => 'home/nav_actu' %>
    </div>


<script type="text/javascript">
  $(document).ready(function(){
    $('.nav-tabs li').first().addClass('active');
    $('.tab-pane').first().addClass('active');
  })
</script>